name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build
        run: |
          npm ci
          # npm run build

      - name: Zip source
        run: |
          zip -r deploy.zip . -x ".git/*" ".github/*" "tests/*" "*.log" "node_modules/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload bundle to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.EB_BUCKET }}/$GITHUB_SHA.zip

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "$GITHUB_SHA" \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="$GITHUB_SHA.zip"

      - name: Update EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "$GITHUB_SHA"
